# Assignment 1: Aufgabe B

# B KNN MNIST -done
_3 points_

- What is the error rate of KNN on the test set?
- What is the error rate for each label (number)?

Do for k = 2, 4, 8

- How does the choice of k influence the results?

## Imports & Variablen

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.manifold import TSNE
import scipy.spatial.distance
from sklearn.metrics import classification_report
from sklearn import metrics #needed for differentiating accuracy for each digit
from sklearn.neighbors import KNeighborsClassifier

train_size = 10000
test_size = 100
k = [2,4,8]
plt.set_cmap('gray')


## Train and reshape

In [2]:
train = tf.keras.datasets.mnist.load_data()[0] #load training data train
X_train, Y_train = train[0], train[1]  #split it into X and Y data

test = tf.keras.datasets.mnist.load_data()[1]#load test data
X_test, Y_test = test[0], test[1] #split it into X and Y data

n_train = X_train.shape[0] #Dimension 1: nr of lines (?)-> 60 000
n_test = X_test.shape[0] #Dimension 1: nr of lines (?)-> 10 000

m = X_train.shape[1]**2 


In [3]:
X_train = X_train.reshape([n_train, m])
X_test = X_test.reshape([n_test, m])

In [4]:
idx = np.random.randint(n_train, size=train_size) #random index: with n_train being the Lowest (signed) integer to be drawn 
#from the distribution and size being the Output shape. 
x_train_sample = X_train[idx] #choose 1 sample in trainingsdata with this randomly-chosen index. 
y_train_sample = Y_train[idx] #corresponding entry on Y-axis. 

In [5]:
# do the same for test data
idx = np.random.randint(n_test, size=test_size) 
x_test_sample = X_test[idx]
y_test_sample = Y_test[idx]

In [6]:
#now: use the Scikit-learn algorithm

## KNN

In [7]:
def runKnn(k):
    neigh = KNeighborsClassifier(n_neighbors=k,n_jobs=-1)#since we have to try it with k = 2,4,8
    neigh.fit(x_train_sample, y_train_sample) 
    pred = neigh.predict(x_test_sample)
    print ("Confusion Matrix for each number:")
    print("")
    print(metrics.confusion_matrix(y_test_sample,pred))
    print("")
    print ("Error rate:")
    print(1-neigh.score(x_test_sample, y_test_sample))

## For K = 2

In [8]:
runKnn(k[0])

Confusion Matrix for each number:

[[12  0  0  0  0  0  0  0  0  0]
 [ 0 17  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  1]
 [ 0  0  0  1  0 11  0  0  0  0]
 [ 1  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  6  0  0]
 [ 0  0  0  0  0  0  0  0  7  0]
 [ 0  0  0  0  0  0  0  2  0  5]]

Error rate:
0.050000000000000044


## For K = 4

In [9]:
runKnn(k[1])

Confusion Matrix for each number:

[[12  0  0  0  0  0  0  0  0  0]
 [ 0 17  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  1]
 [ 0  0  0  1  0 11  0  0  0  0]
 [ 1  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  6  0  0]
 [ 0  0  0  1  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  0  0  7]]

Error rate:
0.040000000000000036


## For K = 8

In [10]:
runKnn(k[2])

Confusion Matrix for each number:

[[12  0  0  0  0  0  0  0  0  0]
 [ 0 17  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0]
 [ 0  0  0  0  0 12  0  0  0  0]
 [ 0  0  0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  0  0  6  0  0]
 [ 0  0  0  0  0  0  0  0  7  0]
 [ 0  0  0  0  0  0  0  1  0  6]]

Error rate:
0.010000000000000009


## Zusammenfassung
Bei k = 8 wird eine niedrigere Error rate erreicht als bei k = 2 oder k = 4